name: artemis
version: 6.18.4

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  build_config: ^0.4.5
  build: ^2.0.0
  code_builder: ^3.2.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  equatable: ^2.0.3
  glob: ^2.0.0
  gql_code_gen: ^0.1.3
  gql_dedupe_link: ^1.0.10
  gql_exec: ^0.2.4
  gql_http_link: ^0.3.2
  gql_link: ^0.3.1-alpha
  gql: ^0.13.0
  http: ^0.12.2
  json_annotation: ^4.0.1
  meta: ^1.7.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  yaml: ^3.1.0

dependency_overrides:
  build: ^2.0.0
  glob: ^2.0.0
  dart_style: ^2.0.0
  gql: ^0.13.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^1.10.11
  build_test: ^1.3.2
  json_serializable: ^4.1.0
  build_resolvers: ^1.3.5
  pedantic: ^1.11.1
  test: ^1.15.7
  logging: ^1.0.2
